### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by steve-mcintyre** [Solomoriah/gdmodule#4]
Hi!

I'm using your code in visualising VLANs in VLANd. (https://git.lavasoftware.org/lava/vland/) and I'm being pushed to update to python 3. Is there any chance of seeing a py3 version of gdmodule please, or should I be looking to replace the graphics library I'm using?

Thanks!

**Comment by steve-mcintyre** [comment]
In fact, I've just moved over to using PIL for my next release. Therefore closing this.

**Comment by Solomoriah** [comment]
Sorry I didn't get back to you on this.  I took over gdmodule when I needed it updated; I've since stopped using it myself, and it no longer gets much attention.
